In [15]:
'''determine the portion of the interview in which the action unit got activated the most'''
import os
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
path="C://Users//vandi//Documents//daicwoz_dataset//action_units_trial//"
target = pd.read_csv("C://Users//vandi//Documents//daicwoz_dataset//au_test.csv")
files=os.listdir(path)
print(files)
#print(target.participant[1])
df = pd.DataFrame(columns=["participant","AU01_r", "AU02_r", "AU04_r", "AU05_r", "AU06_r", "AU09_r", "AU10_r", "AU12_r", "AU14_r", "AU15_r", "AU17_r", "AU20_r", "AU25_r", "AU26_r", "AU23_c", "AU28_c", "AU45_c","target"])

['302_CLNF_AUs.txt', '303_CLNF_AUs.txt', '304_CLNF_AUs.txt', '372_CLNF_AUs.txt', '374_CLNF_AUs.txt', '375_CLNF_AUs.txt', '376_CLNF_AUs.txt', '377_CLNF_AUs.txt', '379_CLNF_AUs.txt', '380_CLNF_AUs.txt', '381_CLNF_AUs.txt', '382_CLNF_AUs.txt', '383_CLNF_AUs.txt', '385_CLNF_AUs.txt', '386_CLNF_AUs.txt', '388_CLNF_AUs.txt', '389_CLNF_AUs.txt', '390_CLNF_AUs.txt', '391_CLNF_AUs.txt', '392_CLNF_AUs.txt', '393_CLNF_AUs.txt', '395_CLNF_AUs.txt', '397_CLNF_AUs.txt', '400_CLNF_AUs.txt', '401_CLNF_AUs.txt', '402_CLNF_AUs.txt', '403_CLNF_AUs.txt', '404_CLNF_AUs.txt', '406_CLNF_AUs.txt', '409_CLNF_AUs.txt', '412_CLNF_AUs.txt', '413_CLNF_AUs.txt', '414_CLNF_AUs.txt', '415_CLNF_AUs.txt', '416_CLNF_AUs.txt', '417_CLNF_AUs.txt', '418_CLNF_AUs.txt', '419_CLNF_AUs.txt', '420_CLNF_AUs.txt', '422_CLNF_AUs.txt', '423_CLNF_AUs.txt', '425_CLNF_AUs.txt', '426_CLNF_AUs.txt', '427_CLNF_AUs.txt', '428_CLNF_AUs.txt', '429_CLNF_AUs.txt', '430_CLNF_AUs.txt', '433_CLNF_AUs.txt', '434_CLNF_AUs.txt', '436_CLNF_AUs.txt',

In [16]:
for i in files:
    print(i[0:3])
    d_newdf={}
    data = pd.read_csv(path+i, sep=",", header=None)
    d_newdf["participant"]=i[0:3]
    
    data.columns = ["frame", "timestamp", "confidence", "success", "AU01_r", "AU02_r", "AU04_r", "AU05_r", "AU06_r", "AU09_r", "AU10_r", "AU12_r", "AU14_r", "AU15_r", "AU17_r", "AU20_r", "AU25_r", "AU26_r","AU04_c","AU12_c", "AU15_c", "AU23_c", "AU28_c", "AU45_c"]
    divide_time=(len(data)*0.033)/2
    temp_df_AU01=data.timestamp[data.AU01_r!=' 0']
    AU01_st=0
    AU01_et=0
    AU01_t=-1
    l_AU01=temp_df_AU01.tolist()
    print(type(l_AU01[1]))
    for j in range(1,len(l_AU01)):
        #if i[0:3]=='372':
           # print(type(l_AU01[j]))
        time=float(l_AU01[j])
        if time<=divide_time:
            AU01_st+=1
        else:
            AU01_et+=1
    if AU01_st>AU01_et:
        AU01_t=0
    else:
        AU01_t=1
    print(AU01_t)
        
    d_newdf["AU01_r"]=AU01_t
    
    temp_df_AU02=data.timestamp[data.AU02_r!=' 0']
    AU02_st=0
    AU02_et=0
    AU02_t=-1
    l_AU02=temp_df_AU02.tolist()
    for j in range(1,len(l_AU02)):
        time=float(l_AU02[j])
        if time<=divide_time:
            AU02_st+=1
        else:
            AU02_et+=1
    if AU02_st>AU02_et:
        AU02_t=0
    else:
        AU02_t=1
    print(AU02_t)   
    d_newdf["AU02_r"]=AU02_t
    
    temp_df_AU04=data.timestamp[data.AU04_r!=' 0']
    AU04_st=0
    AU04_et=0
    AU04_t=-1
    l_AU04=temp_df_AU04.tolist()
    for j in range(1,len(l_AU04)):
        time=float(l_AU04[j])
        if time<=divide_time:
            AU04_st+=1
        else:
            AU04_et+=1
    if AU04_st>AU04_et:
        AU04_t=0
    else:
        AU04_t=1
    print(AU04_t) 
    d_newdf["AU04_r"]=AU04_t
    
    temp_df_AU05=data.timestamp[data.AU05_r!=' 0']
    AU05_st=0
    AU05_et=0
    AU05_t=-1
    l_AU05=temp_df_AU05.tolist()
    for j in range(1,len(l_AU05)):
        time=float(l_AU05[j])
        if time<=divide_time:
            AU05_st+=1
        else:
            AU05_et+=1
    if AU05_st>AU05_et:
        AU05_t=0
    else:
        AU05_t=1
    print(AU05_t) 
    d_newdf["AU05_r"]=AU05_t
    
    temp_df_AU06=data.timestamp[data.AU06_r!=' 0']
    AU06_st=0
    AU06_et=0
    AU06_t=-1
    l_AU06=temp_df_AU06.tolist()
    for j in range(1,len(l_AU06)):
        time=float(l_AU06[j])
        if time<=divide_time:
            AU06_st+=1
        else:
            AU06_et+=1
    if AU06_st>AU06_et:
        AU06_t=0
    else:
        AU06_t=1
    print(AU06_t) 
    d_newdf["AU06_r"]=AU06_t
    
    temp_df_AU09=data.timestamp[data.AU09_r!=' 0']
    AU09_st=0
    AU09_et=0
    AU09_t=-1
    l_AU09=temp_df_AU09.tolist()
    for j in range(1,len(l_AU09)):
        time=float(l_AU09[j])
        if time<=divide_time:
            AU09_st+=1
        else:
            AU09_et+=1
    if AU09_st>AU09_et:
        AU09_t=0
    else:
        AU09_t=1
    print(AU09_t) 
    d_newdf["AU09_r"]=AU09_t
    
    temp_df_AU10=data.timestamp[data.AU10_r!=' 0']
    AU10_st=0
    AU10_et=0
    AU10_t=-1
    l_AU10=temp_df_AU10.tolist()
    for j in range(1,len(l_AU10)):
        time=float(l_AU10[j])
        if time<=divide_time:
            AU10_st+=1
        else:
            AU10_et+=1
    if AU10_st>AU10_et:
        AU10_t=0
    else:
        AU10_t=1
    print(AU10_t) 
    d_newdf["AU10_r"]=AU10_t
    
    temp_df_AU12=data.timestamp[data.AU12_r!=' 0']
    AU12_st=0
    AU12_et=0
    AU12_t=-1
    l_AU12=temp_df_AU12.tolist()
    for j in range(1,len(l_AU12)):
        time=float(l_AU12[j])
        if time<=divide_time:
            AU12_st+=1
        else:
            AU12_et+=1
    if AU12_st>AU12_et:
        AU12_t=0
    else:
        AU12_t=1
    print(AU12_t) 
    d_newdf["AU12_r"]=AU12_t
    
    temp_df_AU14=data.timestamp[data.AU14_r!=' 0']
    AU14_st=0
    AU14_et=0
    AU14_t=-1
    l_AU14=temp_df_AU14.tolist()
    for j in range(1,len(l_AU14)):
        time=float(l_AU14[j])
        if time<=divide_time:
            AU14_st+=1
        else:
            AU14_et+=1
    if AU04_st>AU14_et:
        AU14_t=0
    else:
        AU14_t=1
    print(AU14_t) 
    d_newdf["AU14_r"]=AU14_t
    
    temp_df_AU15=data.timestamp[data.AU15_r!=' 0']
    AU15_st=0
    AU15_et=0
    AU15_t=-1
    l_AU15=temp_df_AU15.tolist()
    for j in range(1,len(l_AU15)):
        time=float(l_AU15[j])
        if time<=divide_time:
            AU15_st+=1
        else:
            AU15_et+=1
    if AU15_st>AU15_et:
        AU15_t=0
    else:
        AU15_t=1
    print(AU15_t) 
    d_newdf["AU15_r"]=AU15_t
    
    temp_df_AU17=data.timestamp[data.AU17_r!=' 0']
    AU17_st=0
    AU17_et=0
    AU17_t=-1
    l_AU17=temp_df_AU17.tolist()
    for j in range(1,len(l_AU17)):
        time=float(l_AU17[j])
        if time<=divide_time:
            AU17_st+=1
        else:
            AU17_et+=1
    if AU17_st>AU17_et:
        AU17_t=0
    else:
        AU17_t=1
    print(AU17_t) 
    d_newdf["AU17_r"]=AU17_t
    
    temp_df_AU20=data.timestamp[data.AU20_r!=' 0']
    AU20_st=0
    AU20_et=0
    AU20_t=-1
    l_AU20=temp_df_AU20.tolist()
    for j in range(1,len(l_AU20)):
        time=float(l_AU20[j])
        if time<=divide_time:
            AU20_st+=1
        else:
            AU20_et+=1
    if AU20_st>AU20_et:
        AU20_t=0
    else:
        AU20_t=1
    print(AU20_t) 
    d_newdf["AU20_r"]=AU20_t
    
    temp_df_AU25=data.timestamp[data.AU25_r!=' 0']
    AU25_st=0
    AU25_et=0
    AU25_t=-1
    l_AU25=temp_df_AU25.tolist()
    for j in range(1,len(l_AU25)):
        time=float(l_AU25[j])
        if time<=divide_time:
            AU25_st+=1
        else:
            AU25_et+=1
    if AU25_st>AU25_et:
        AU25_t=0
    else:
        AU25_t=1
    print(AU25_t) 
    d_newdf["AU25_r"]=AU25_t
    
    temp_df_AU26=data.timestamp[data.AU26_r!=' 0']
    AU26_st=0
    AU26_et=0
    AU26_t=-1
    l_AU26=temp_df_AU26.tolist()
    for j in range(1,len(l_AU26)):
        time=float(l_AU26[j])
        if time<=divide_time:
            AU26_st+=1
        else:
            AU26_et+=1
    if AU26_st>AU26_et:
        AU26_t=0
    else:
        AU26_t=1
    print(AU26_t) 
    d_newdf["AU26_r"]=AU26_t
    
    temp_df_AU23=data.timestamp[data.AU23_c!=' 0']
    AU23_st=0
    AU23_et=0
    AU23_t=-1
    l_AU23=temp_df_AU23.tolist()
    for j in range(1,len(l_AU23)):
        time=float(l_AU23[j])
        if time<=divide_time:
            AU23_st+=1
        else:
            AU23_et+=1
    if AU23_st>AU23_et:
        AU23_t=0
    else:
        AU23_t=1
    print(AU23_t) 
    d_newdf["AU23_c"]=AU23_t
    
    temp_df_AU28=data.timestamp[data.AU28_c!=' 0']
    AU28_st=0
    AU28_et=0
    AU28_t=-1
    l_AU28=temp_df_AU28.tolist()
    for j in range(1,len(l_AU28)):
        time=float(l_AU28[j])
        if time<=divide_time:
            AU28_st+=1
        else:
            AU28_et+=1
    if AU28_st>AU28_et:
        AU28_t=0
    else:
        AU28_t=1
    print(AU28_t) 
    d_newdf["AU28_c"]=AU28_t    
    
    temp_df_AU45=data.timestamp[data.AU45_c!=' 0']
    AU45_st=0
    AU45_et=0
    AU45_t=-1
    l_AU45=temp_df_AU45.tolist()
    for j in range(1,len(l_AU45)):
        time=float(l_AU45[j])
        if time<=divide_time:
            AU45_st+=1
        else:
            AU45_et+=1
    if AU45_st>AU45_et:
        AU45_t=0
    else:
        AU45_t=1
    print(AU45_t) 
    d_newdf["AU45_c"]=AU45_t
    
    target_newdf=target.PHQ8_depression[target.participant==int(i[0:3])]
    #target_newdf=list(target_newdf)
    target_newdf=target_newdf.tolist()
    print(target_newdf)
    if target_newdf[0]<10:
       # print("Hi")
        target_newdf[0]=0
    else:
        target_newdf[0]=1
    d_newdf["target"]=target_newdf[0]
    
    df = df.append(d_newdf, ignore_index=True)

302
<class 'str'>
1
0
0
1
0
1
0
1
0
0
0
1
1
1
0
1
0
[1]
303
<class 'str'>
1
0
1
0
0
0
1
0
0
1
1
1
0
0
0
1
1
[0]
304
<class 'str'>
0
0
1
1
1
0
1
0
1
1
1
0
0
1
1
1
1
[6]
372


C:\Users\vandi\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


<class 'str'>
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
[13]
374
<class 'str'>
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
[2]
375
<class 'str'>
0
0
0
0
0
0
0
0
0
0
0
1
0
1
0
1
1
[5]
376
<class 'str'>
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
[12]
377
<class 'str'>
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
[16]
379
<class 'str'>
0
0
1
0
0
0
0
0
1
0
0
1
1
0
1
1
0
[2]
380
<class 'str'>
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
[10]
381
<class 'str'>
0
1
1
0
0
0
0
0
1
1
0
1
1
1
1
1
0
[16]
382
<class 'str'>
0
1
1
1
0
0
0
0
0
1
0
0
0
1
0
1
1
[0]
383
<class 'str'>
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
[7]
385
<class 'str'>
0
0
1
0
1
0
1
0
1
0
1
0
1
1
0
1
1
[8]
386
<class 'str'>
1
0
1
1
0
0
0
0
1
1
1
1
1
1
1
0
1
[11]
388
<class 'str'>
1
0
1
1
0
0
0
0
1
0
1
0
0
1
1
0
0
[17]
389
<class 'str'>
1
1
0
1
0
0
0
0
0
1
1
1
0
1
0
1
0
[14]
390
<class 'str'>
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
[9]
391
<class 'str'>
1
1
1
1
0
0
0
1
0
1
0
1
1
1
1
1
1
[9]
392
<class 'str'>
0
0
1
1
0
0
0
0
1
1
0
1
1
0
1
1
1
[1]
393
<class 'str'>
0
0
1
1
1
0
1
0
1
1
1
0
0


In [17]:
df

participant AU01_r AU02_r AU04_r AU05_r AU06_r AU09_r AU10_r AU12_r AU14_r  \
0          302      1      0      0      1      0      1      0      1      0   
1          303      1      0      1      0      0      0      1      0      0   
2          304      0      0      1      1      1      0      1      0      1   
3          372      1      1      1      1      1      1      1      1      1   
4          374      1      1      1      1      1      1      1      1      1   
5          375      0      0      0      0      0      0      0      0      0   
6          376      1      1      1      1      1      1      1      1      1   
7          377      1      1      1      1      1      1      1      1      1   
8          379      0      0      1      0      0      0      0      0      1   
9          380      1      1      1      1      1      1      1      1      1   
10         381      0      1      1      0      0      0      0      0      1   
11         382      0      1      1      1      0      0      0      0      0   
12         383      1      1      1      1      1      1      1      1      1   
13         385      0      0      1      0      1      0      1      0      1   
14         386      1      0      1      1      0      0      0      0      1   
15         388      1      0      1      1      0      0      0      0      1   
16         389      1      1      0      1      0      0      0      0      0   
17         390      1      1      1      1      1      1      1      1      1   
18         391      1      1      1      1      0      0      0      1      0   
19         392      0      0      1      1      0      0      0      0      1   
20         393      0      0      1      1      1      0      1      0      1   
21         395      1      0      0      0      0      0      0      0      0   
22         397      1      0      0      1      1      0      1      1      1   
23         400      1      1      1      0      0      1      0      0      0   
24         401      1      0      1      1      0      1      0      0      0   
25         402      1      0      0      1      0      1      0      0      0   
26         403      0      0      1      1      0      0      0      0      1   
27         404      1      1      1      1      1      0      1      1      1   
28         406      0      1      1      1      1      1      1      1      1   
29         409      1      1      1      1      1      1      1      1      1   
30         412      1      1      1      1      0      0      0      0      1   
31         413      0      0      1      1      1      0      1      1      1   
32         414      1      0      1      1      0      0      0      0      1   
33         415      0      0      1      0      0      0      0      1      1   
34         416      0      1      0      1      0      0      0      0      0   
35         417      1      1      0      1      0      0      0      0      0   
36         418      0      0      0      0      0      0      0      0      0   
37         419      1      0      0      1      0      1      0      0      0   
38         420      1      0      1      0      0      1      0      0      1   
39         422      1      1      0      1      1      1      1      1      0   
40         423      1      1      0      1      0      0      0      0      1   
41         425      1      0      0      1      1      1      1      0      0   
42         426      1      1      1      1      1      0      1      1      1   
43         427      0      1      1      1      0      1      1      0      1   
44         428      1      0      0      0      0      0      0      0      1   
45         429      1      0      1      0      1      0      1      1      1   
46         430      1      0      0      0      0      0      0      0      0   
47         433      1      0      0      1      0      0      0      0      0   
48         434      1      1      

In [18]:
a=np.array(df)
y=a[:,18]
x = np.column_stack((df.AU01_r,df.AU02_r,df.AU04_r,df.AU05_r,df.AU06_r,df.AU09_r,df.AU10_r,df.AU12_r,df.AU14_r,df.AU15_r,df.AU17_r,df.AU20_r,df.AU25_r,df.AU26_r,df.AU23_c,df.AU28_c,df.AU45_c))
#print (x),(y)
y=y.astype('int')
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)
print(y)

[0 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1
 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1]


In [22]:
clf = SVC(kernel='linear') 
# fitting x samples and y classes 
clf.fit(x_train, y_train) 
y_pred = clf.predict(x_test)
print(y_test)
print(y_pred)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred, labels=[0,1]))
print(accuracy_score(y_test, y_pred))

[0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0]
[1 0 0 1 1 0 1 0 1 1 0 0 1 1 1 1 0 0]
              precision    recall  f1-score   support

           0       0.88      0.50      0.64        14
           1       0.30      0.75      0.43         4

    accuracy                           0.56        18
   macro avg       0.59      0.62      0.53        18
weighted avg       0.75      0.56      0.59        18

[[7 7]
 [1 3]]
0.5555555555555556


In [23]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=20, random_state=0)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
print(y_test)
print(y_pred)

[0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0]


In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[9 5]
 [3 1]]
              precision    recall  f1-score   support

           0       0.75      0.64      0.69        14
           1       0.17      0.25      0.20         4

    accuracy                           0.56        18
   macro avg       0.46      0.45      0.45        18
weighted avg       0.62      0.56      0.58        18

0.5555555555555556
