In [8]:
import os
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
path="C://Users//vandi//Documents//daicwoz_dataset//action_units_trial//"
target = pd.read_csv("C://Users//vandi//Documents//daicwoz_dataset//au_test.csv")
files=os.listdir(path)
print(files)
#print(target.participant[1])
df = pd.DataFrame(columns=["participant","AU01_r", "AU02_r", "AU04_r", "AU05_r", "AU06_r", "AU09_r", "AU10_r", "AU12_r", "AU14_r", "AU15_r", "AU17_r", "AU20_r", "AU25_r", "AU26_r", "AU23_c", "AU28_c", "AU45_c","target"])

['302_CLNF_AUs.txt', '303_CLNF_AUs.txt', '304_CLNF_AUs.txt', '372_CLNF_AUs.txt', '374_CLNF_AUs.txt', '375_CLNF_AUs.txt', '376_CLNF_AUs.txt', '377_CLNF_AUs.txt', '379_CLNF_AUs.txt', '380_CLNF_AUs.txt', '381_CLNF_AUs.txt', '382_CLNF_AUs.txt', '383_CLNF_AUs.txt', '385_CLNF_AUs.txt', '386_CLNF_AUs.txt', '388_CLNF_AUs.txt', '389_CLNF_AUs.txt', '390_CLNF_AUs.txt', '391_CLNF_AUs.txt', '392_CLNF_AUs.txt', '393_CLNF_AUs.txt', '395_CLNF_AUs.txt', '397_CLNF_AUs.txt', '400_CLNF_AUs.txt', '401_CLNF_AUs.txt', '402_CLNF_AUs.txt', '403_CLNF_AUs.txt', '404_CLNF_AUs.txt', '406_CLNF_AUs.txt', '409_CLNF_AUs.txt', '412_CLNF_AUs.txt', '413_CLNF_AUs.txt', '414_CLNF_AUs.txt', '415_CLNF_AUs.txt', '416_CLNF_AUs.txt', '417_CLNF_AUs.txt', '418_CLNF_AUs.txt', '419_CLNF_AUs.txt', '420_CLNF_AUs.txt', '422_CLNF_AUs.txt', '423_CLNF_AUs.txt', '425_CLNF_AUs.txt', '426_CLNF_AUs.txt', '427_CLNF_AUs.txt', '428_CLNF_AUs.txt', '429_CLNF_AUs.txt', '430_CLNF_AUs.txt', '433_CLNF_AUs.txt', '434_CLNF_AUs.txt', '436_CLNF_AUs.txt',

In [9]:
for i in files:
    d_newdf={}
    data = pd.read_csv(path+i, sep=",", header=None)
    d_newdf["participant"]=i[0:3]
    
    data.columns = ["frame", "timestamp", "confidence", "success", "AU01_r", "AU02_r", "AU04_r", "AU05_r", "AU06_r", "AU09_r", "AU10_r", "AU12_r", "AU14_r", "AU15_r", "AU17_r", "AU20_r", "AU25_r", "AU26_r","AU04_c","AU12_c", "AU15_c", "AU23_c", "AU28_c", "AU45_c"]
    temp_df_AU01=data.AU01_r[data.AU01_r!=' 0']
    ratio_AU01=temp_df_AU01.count()/len(data)
    d_newdf["AU01_r"]=ratio_AU01
    
    temp_df_AU02=data.AU02_r[data.AU02_r!=' 0']
    ratio_AU02=temp_df_AU02.count()/len(data)
    d_newdf["AU02_r"]=ratio_AU02
    
    temp_df_AU04=data.AU04_r[data.AU04_r!=' 0']
    ratio_AU04=temp_df_AU04.count()/len(data)
    d_newdf["AU04_r"]=ratio_AU04
    
    temp_df_AU05=data.AU05_r[data.AU05_r!=' 0']
    ratio_AU05=temp_df_AU05.count()/len(data)
    d_newdf["AU05_r"]=ratio_AU05
    
    temp_df_AU06=data.AU06_r[data.AU06_r!=' 0']
    ratio_AU06=temp_df_AU06.count()/len(data)
    d_newdf["AU06_r"]=ratio_AU06
    
    temp_df_AU09=data.AU09_r[data.AU09_r!=' 0']
    ratio_AU09=temp_df_AU09.count()/len(data)
    d_newdf["AU09_r"]=ratio_AU09
    
    temp_df_AU10=data.AU10_r[data.AU10_r!=' 0']
    ratio_AU10=temp_df_AU10.count()/len(data)
    d_newdf["AU10_r"]=ratio_AU10
    
    temp_df_AU12=data.AU12_r[data.AU12_r!=' 0']
    ratio_AU12=temp_df_AU12.count()/len(data)
    d_newdf["AU12_r"]=ratio_AU12
    
    temp_df_AU14=data.AU14_r[data.AU10_r!=' 0']
    ratio_AU14=temp_df_AU14.count()/len(data)
    d_newdf["AU14_r"]=ratio_AU14
    
    temp_df_AU15=data.AU15_r[data.AU15_r!=' 0']
    ratio_AU15=temp_df_AU15.count()/len(data)
    d_newdf["AU15_r"]=ratio_AU15
    
    temp_df_AU17=data.AU17_r[data.AU17_r!=' 0']
    ratio_AU17=temp_df_AU17.count()/len(data)
    d_newdf["AU17_r"]=ratio_AU17
    
    temp_df_AU20=data.AU20_r[data.AU20_r!=' 0']
    ratio_AU20=temp_df_AU20.count()/len(data)
    d_newdf["AU20_r"]=ratio_AU20
    
    temp_df_AU25=data.AU25_r[data.AU25_r!=' 0']
    ratio_AU25=temp_df_AU25.count()/len(data)
    d_newdf["AU25_r"]=ratio_AU25
    
    temp_df_AU26=data.AU26_r[data.AU26_r!=' 0']
    ratio_AU26=temp_df_AU26.count()/len(data)
    d_newdf["AU26_r"]=ratio_AU26
    
    temp_df_AU23=data.AU23_c[data.AU23_c!=' 0']
    ratio_AU23=temp_df_AU23.count()/len(data)
    d_newdf["AU23_c"]=ratio_AU23
    
    temp_df_AU28=data.AU28_c[data.AU28_c!=' 0']
    ratio_AU28=temp_df_AU28.count()/len(data)
    d_newdf["AU28_c"]=ratio_AU28    
    
    temp_df_AU45=data.AU45_c[data.AU45_c!=' 0']
    ratio_AU45=temp_df_AU45.count()/len(data)
    d_newdf["AU45_c"]=ratio_AU45
    
    target_newdf=target.PHQ8_depression[target.participant==int(i[0:3])]
    #target_newdf=list(target_newdf)
    target_newdf=target_newdf.tolist()
    print(target_newdf)
    if target_newdf[0]<10:
       # print("Hi")
        target_newdf[0]=0
    else:
        target_newdf[0]=1
    d_newdf["target"]=target_newdf[0]
    
    df = df.append(d_newdf, ignore_index=True)

    

[1]
[0]
[6]
[13]
[2]
[5]
[12]
[16]
[2]
[10]
[16]
[0]
[7]
[8]
[11]
[17]
[14]
[9]
[9]
[1]
[2]
[7]
[5]
[7]
[9]
[11]
[0]
[0]
[2]
[10]
[12]
[10]
[16]
[3]
[3]
[7]
[10]
[3]
[3]
[12]
[0]
[6]
[20]
[5]
[0]
[1]
[3]
[10]
[2]
[0]
[0]
[1]
[19]


In [10]:
df
#target[target.PHQ8_depression>=10]




participant    AU01_r    AU02_r    AU04_r    AU05_r    AU06_r    AU09_r  \
0          302  0.484732  0.530294  0.584078  0.325670  0.180344  0.495889   
1          303  0.518569  0.340560  0.564669  0.323683  0.240073  0.401948   
2          304  0.500021  0.418275  0.357891  0.362516  0.194231  0.421765   
3          372  0.631878  0.590572  0.609353  0.605676  0.529207  0.584143   
4          374  0.515661  0.479887  0.577345  0.303505  0.347795  0.444761   
5          375  0.367763  0.348500  0.483447  0.299780  0.325911  0.437946   
6          376  0.314172  0.404900  0.470087  0.136223  0.250772  0.261560   
7          377  0.563911  0.568704  0.644259  0.373708  0.345704  0.545895   
8          379  0.235848  0.239107  0.209506  0.182166  0.095290  0.568516   
9          380  0.644770  0.659163  0.639820  0.660061  0.606035  0.677844   
10         381  0.270791  0.383881  0.482161  0.027538  0.206995  0.309834   
11         382  0.246674  0.101379  0.197460  0.063043  0.073355  0.285293   
12         383  0.574632  0.479757  0.464005  0.301960  0.467851  0.509677   
13         385  0.347813  0.112603  0.415672  0.094581  0.100298  0.213647   
14         386  0.297056  0.280607  0.449400  0.080260  0.263195  0.352594   
15         388  0.403914  0.328962  0.360042  0.234200  0.383422  0.447385   
16         389  0.424925  0.384398  0.365305  0.155675  0.235051  0.402651   
17         390  0.635318  0.409665  0.584832  0.260269  0.263193  0.473197   
18         391  0.446682  0.417034  0.397922  0.184064  0.224640  0.343085   
19         392  0.145943  0.078691  0.215738  0.034313  0.206181  0.213552   
20         393  0.396244  0.424121  0.445914  0.278656  0.276858  0.328220   
21         395  0.589153  0.161250  0.393493  0.354286  0.207167  0.314217   
22         397  0.532343  0.478077  0.542238  0.280350  0.460804  0.409441   
23         400  0.437467  0.401423  0.434762  0.235189  0.241665  0.361573   
24         401  0.518303  0.442272  0.480341  0.327209  0.196018  0.445590   
25         402  0.481760  0.333320  0.377360  0.206720  0.344120  0.393280   
26         403  0.353375  0.304958  0.283241  0.086016  0.234244  0.334596   
27         404  0.549394  0.529819  0.530556  0.291471  0.372454  0.466820   
28         406  0.435794  0.464977  0.354666  0.324606  0.226486  0.417740   
29         409  0.336788  0.202841  0.202002  0.081388  0.222534  0.305956   
30         412  0.310696  0.197316  0.224232  0.046636  0.280591  0.491871   
31         413  0.246464  0.176146  0.119604  0.121711  0.044070  0.143612   
32         414  0.371009  0.232520  0.284055  0.155013  0.367589  0.372499   
33         415  0.486766  0.415599  0.567281  0.266735  0.452826  0.560750   
34         416  0.293133  0.290708  0.348834  0.072715  0.162407  0.203595   
35         417  0.375691  0.370012  0.450754  0.095784  0.213832  0.459592   
36         418  0.381292  0.380221  0.451241  0.298430  0.211438  0.351183   
37         419  0.382788  0.355682  0.322766  0.254579  0.204266  0.315962   
38         420  0.254990  0.173548  0.186099  0.083613  0.160713  0.414193   
39         422  0.518332  0.438536  0.776424  0.495180  0.274750  0.573676   
40         423  0.354898  0.250544  0.299240  0.180127  0.330868  0.360989   
41         425  0.355030  0.275249  0.381152  0.085063  0.109857  0.360283   
42         426  0.449096  0.309006  0.440576  0.163237  0.197860  0.322389   
43         427  0.471076  0.286829  0.395488  0.349455  0.241101  0.368801   
44         428  0.371356  0.332355  0.412912  0.240061  0.334296  0.383661   
45         429  0.422843  0.373795  0.555958  0.294288  0.239043  0.469245   
46         430  0.489382  0.436457  0.514029  0.093123  0.392811  0.360646   
47         433  0.237654  0.257192  0.200906  0.078317  0.171932  0.275357   
48         434  0.565534  0.566039  0.509596  0.526340  0.430880  0.574675   
49         436  0.250363  0.235052  0.532610  0.057321  0.101754  0.340198   
50         437  0.398933 

In [11]:
a=np.array(df)
y=a[:,18]
x = np.column_stack((df.AU01_r,df.AU02_r,df.AU04_r,df.AU05_r,df.AU06_r,df.AU09_r,df.AU10_r,df.AU12_r,df.AU14_r,df.AU15_r,df.AU17_r,df.AU20_r,df.AU25_r,df.AU26_r,df.AU23_c,df.AU28_c,df.AU45_c))
#print (x),(y)
y=y.astype('int')
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)
print(y)



[0 0 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1
 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1]


In [19]:
clf = SVC(kernel='linear') 
# fitting x samples and y classes 
clf.fit(x_train, y_train) 
y_pred = clf.predict(x_test)
print(y_test)
print(y_pred)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred, labels=[0,1]))

[0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
              precision    recall  f1-score   support

           0       0.78      1.00      0.88        14
           1       0.00      0.00      0.00         4

    accuracy                           0.78        18
   macro avg       0.39      0.50      0.44        18
weighted avg       0.60      0.78      0.68        18

[[14  0]
 [ 4  0]]


C:\Users\vandi\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [26]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=20, random_state=0)
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
print(y_test)
print(y_pred)

[0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]


In [25]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))


[[14  0]
 [ 3  1]]
              precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.25      0.40         4

    accuracy                           0.83        18
   macro avg       0.91      0.62      0.65        18
weighted avg       0.86      0.83      0.79        18

0.8333333333333334
